jobs:
  build:
    env:
      JAVA_OPTS: -Xmx3g
      PROFILES: ''
      SPARK_1_6: http://d3kbcqa49mib13.cloudfront.net/spark-1.6.3-bin-hadoop2.6.tgz
      SPARK_2_0: http://d3kbcqa49mib13.cloudfront.net/spark-2.0.2-bin-hadoop2.7.tgz
      SPARK_2_1: http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz
      SPARK_2_3: https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz
      STANDARD_BUILD_OPTS: -Dmaven.javadoc.skip=true -B -V
      TEST_MODULES: core,engine
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 10
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8.0.392+8
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Install dependencies
      run: 'sudo apt-get update

        sudo apt-get install ocl-icd-libopencl1

        wget https://github.com/viennacl/viennacl-dev/archive/release-1.7.1.zip

        unzip -qq release-1.7.1.zip

        sudo cp -r viennacl-dev-release-1.7.1/viennacl /usr/include/viennacl

        sudo cp -r viennacl-dev-release-1.7.1/CL /usr/include/CL

        sudo apt-get install openssh-client

        sudo apt-get install openssh-server

        ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa

        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

        '
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package $STANDARD_BUILD_OPTS -DskipTests -DskipCli
    - continue-on-error: true
      name: Setup Spark
      run: 'echo $SPARK_2_3

        wget $SPARK_2_3

        tar -xzf *tgz

        spark*/sbin/start-all.sh

        '
    - continue-on-error: true
      name: Run tests with Spark
      run: mvn test -pl $TEST_MODULES $PROFILES -Dtest.spark.master=spark://localhost:7077
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___mahout.yml
