jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        GEM_HOME: ${RUBY_PATH}/gems
        RUBY_PATH: ~/shared/.rvm
        WORKDIR: /tmp/mahout-site
      name: Build Website
      run: "git config user.name \"GitHub Actions Bot\"\ngit config user.email \"\
        <>\"\n./website/build_site.sh\nrm -rf *\ngit checkout asf-site\ncp -r $WORKDIR/*\
        \ .\ngit add .\ngit commit -m \"Automatic Site Publish by Buildbot\"\ngit\
        \ push \n"
name: Website
on:
  repository_dispatch:
    types: trigger-ga___website.yml
